# Mini Project

In [2]:
import numpy as np

# Step 1 : Read the Data!

In [4]:
# Loading the data
data = np.genfromtxt('makeSenseOfCensus.csv', delimiter=",", skip_header=1)

# printing the data

print("\nData: \n\n", data)


Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


In [5]:
# Printing the Data Type of the data
print("\n Type of data: \n\n",type(data))


 Type of data: 

 <class 'numpy.ndarray'>


# Step 2 : Append the Data
## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [6]:
new_record = [[50,9,4,1,0,0,40,0]]
new_data = np.concatenate((data,new_record),axis=0)
print(new_data)

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]
 [50.  9.  4. ...  0. 40.  0.]]


In [7]:
# Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.
age = new_data[:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

In [8]:
# Find the max age and store it in a variable called 'max_age'.
max_age = age.max()
print('Maximum age ',max_age)

Maximum age  90.0


In [10]:
#Find the min age and store it in a variable called 'min_age'.
min_age = age.min()
print('Minimum age ',min_age)

Minimum age  17.0


In [11]:
# Find the mean of the age and store it in a variable called 'age_mean'.
age_mean = age.mean()
print('Average age ',age_mean)

Average age  38.06293706293706


In [12]:
# Find the standard deviation of the age and store it in a variable called 'age_std'
age_std = age.std()
print('Standard Deviation of age ',age_std)

Standard Deviation of age  13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

In [13]:
race = new_data[:,2]
race_0 = race[race==0]
race_1 = race[race==1]
race_2 = race[race==2]
race_3 = race[race==3]
race_4 = race[race==4]

In [15]:
# Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively
len_0 = len(race_0)
len_1 = len(race_1)
len_2 = len(race_2)
len_3 = len(race_3)
len_4 = len(race_4)
print(len_0, len_1, len_2, len_3, len_4)

10 27 110 6 848


In [16]:
# Find out which is the race with the minimum no. of citizens
lenl = [len_0,len_1,len_2,len_3,len_4]
len_arr = np.array(lenl)
print('Minimum no citizens in a race',len_arr.min())

Minimum no citizens in a race 6


In [17]:
# Store the number associated with the minority race in a variable called 'minority_race'
minority_race = len_arr.min()
print(minority_race)

6


In [19]:
if minority_race == len_0:
  minority_race = 0
elif minority_race == len_1:
  minority_race = 1
elif minority_race == len_2:
  minority_race = 2
elif minority_race == len_3:
  minority_race = 3
elif minority_race == len_4:
  minority_race = 4
print('Minority race: ',minority_race)

Minority race:  3


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

In [21]:
# Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 
senior_citizens = age[age>60]
print(len(senior_citizens))

61


In [22]:
# Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'
working_hour = new_data[:,6]
working_hours_sum = np.sum(working_hour[age>60])

print("Total Working hours of senior citizens:", np.sum(working_hour[age>60]))

Total Working hours of senior citizens: 1917.0


In [23]:
# Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'
senior_citizens_len = len(senior_citizens)
print(senior_citizens_len)

61


In [24]:
# Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.
avg_working_hours = working_hours_sum/senior_citizens_len
print(avg_working_hours)

31.42622950819672


In [25]:
# Print 'avg_working_hours' and see if the govt. policy is followed.
if avg_working_hours <=25:
    print("Govt policy is followed")
else:
    print("Govt policy is not followed")

Govt policy is not followed


# Step 6: Let's check that higher educated people have better pay in general.

In [26]:
# Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10
edu = new_data[:,1]
high = edu[edu>10]
low = edu[edu<=10]
print(high)
print(low)

[13. 13. 13. 14. 14. 13. 13. 13. 12. 11. 14. 16. 13. 12. 13. 12. 13. 13.
 13. 14. 11. 11. 15. 13. 11. 13. 16. 13. 13. 12. 13. 14. 16. 11. 13. 16.
 12. 14. 13. 14. 13. 15. 11. 13. 13. 13. 13. 12. 12. 13. 12. 14. 11. 11.
 13. 13. 13. 14. 14. 12. 14. 11. 13. 13. 13. 13. 13. 14. 16. 13. 13. 14.
 14. 14. 13. 13. 13. 12. 13. 13. 11. 15. 13. 14. 13. 12. 12. 15. 13. 11.
 13. 13. 14. 14. 13. 12. 13. 14. 15. 13. 13. 13. 13. 13. 14. 13. 12. 12.
 12. 13. 14. 13. 14. 11. 13. 11. 14. 12. 11. 13. 11. 12. 13. 13. 13. 13.
 11. 14. 13. 13. 12. 13. 11. 14. 13. 12. 13. 13. 13. 13. 11. 14. 16. 13.
 14. 14. 13. 12. 14. 13. 12. 11. 12. 13. 13. 14. 13. 11. 13. 12. 13. 13.
 13. 12. 13. 13. 13. 11. 11. 11. 13. 13. 13. 14. 12. 15. 11. 13. 16. 11.
 13. 13. 13. 14. 14. 11. 16. 13. 12. 13. 13. 13. 13. 13. 15. 13. 13. 12.
 14. 14. 13. 13. 13. 15. 13. 11. 13. 13. 13. 13. 16. 16. 13. 16. 14. 14.
 12. 13. 11. 13. 14. 13. 12. 14. 14. 13. 13. 13. 16. 13. 13. 13. 11. 13.
 13. 13. 13. 13. 11. 11. 13. 13. 14. 11. 13. 13. 13

In [27]:
print(len(high))
print(len(low))

327
674


In [28]:
# Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.
income = new_data[:,7]
avg_pay_high = np.mean(income[edu>10])
print(avg_pay_high)
avg_pay_low = np.mean(income[edu<=10])
print(avg_pay_low)

0.42813455657492355
0.13649851632047477
